name = "RandomNames"
uuid = "8038b397-5dcf-48d8-aa29-27c5928dc369"
authors = ["Kai Xu <me@xuk.ai> and contributors"]
version = "1.0.0-DEV"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
